<a href="https://colab.research.google.com/github/VivekOPest/gaia-symbolic-regression/blob/main/02_feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation and Feature Engineering

This notebook prepares the Gaia DR3 dataset for symbolic regression.

Objectives:

- Load the raw Gaia dataset.
- Compute physical quantities from Gaia measurements.
- Select the features required for the machine learning model.
- Save the processed dataset for training.

In [4]:
import pandas as pd
import numpy as np

from pathlib import Path

In [5]:
DATA_PATH = "gaia_sample.csv"

df = pd.read_csv(DATA_PATH)

print(df.shape)

df.head()

(20000, 13)

,source_id,parallax,parallax_error,parallax_over_error,ruwe,phot_g_mean_flux,phot_g_mean_flux_error,phot_g_mean_mag,phot_bp_mean_mag,phot_rp_mean_mag,bp_rp,teff_gspphot,radius_gspphot
0,137341754068386432,0.933154,0.051944,17.964705,1.036885,6783.598485,3.588084,16.108717,16.661566,15.408920,1.252646,4896.8936,0.8375
1,137342166385242112,4.299332,0.022674,189.618150,1.026791,38620.291417,12.237451,14.220328,15.037620,13.338170,1.699450,4397.8647,0.7090
2,137348900893898240,0.796858,0.042952,18.552425,1.002285,9817.506707,3.566114,15.707364,16.114141,15.123431,0.990710,5307.8760,0.7948
3,137351615313312384,1.354746,0.018821,71.981310,1.202068,262440.355661,55.139145,12.139791,12.538257,11.568266,0.969991,5952.5596,2.3795
4,137355326165033472,1.222841,0.056203,21.757740,1.006233,4903.220496,2.882057,16.461163,17.241302,15.604395,1.636908,4525.4976,0.8585

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   source_id               20000 non-null  int64
 1   parallax                20000 non-null  float64
 2   parallax_error          20000 non-null  float64
 3   parallax_over_error     20000 non-null  float64
 4   ruwe                    20000 non-null  float64
 5   phot_g_mean_flux        20000 non-null  float64
 6   phot_g_mean_flux_error  20000 non-null  float64
 7   phot_g_mean_mag         20000 non-null  float64
 8   phot_bp_mean_mag        20000 non-null  float64
 9   phot_rp_mean_mag        20000 non-null  float64
 10  bp_rp                   20000 non-null  float64
 11  teff_gspphot            20000 non-null  float64
 12  radius_gspphot          20000 non-null  float64
dtypes: float64(12), int64(1)
memory usage: 2.0 MB

## Computing Distance

Gaia measures stellar parallax in milliarcseconds.

Distance is computed using

d(pc)=1000/parallax

In [7]:
df["distance_pc"] = 1000 / df["parallax"]

In [8]:
selected = df[
    [
        "teff_gspphot",
        "phot_g_mean_flux",
        "distance_pc",
        "radius_gspphot"
    ]
]

In [9]:
selected.info()

selected.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   teff_gspphot      20000 non-null  float64
 1   phot_g_mean_flux  20000 non-null  float64
 2   distance_pc       20000 non-null  float64
 3   radius_gspphot    20000 non-null  float64
dtypes: float64(4)
memory usage: 625.1 KB

teff_gspphot        0
phot_g_mean_flux    0
distance_pc         0
radius_gspphot      0
dtype: int64

In [10]:
selected = selected.dropna()

print(selected.shape)

(20000, 4)

In [11]:
selected.to_csv(
    "gaia_features.csv",
    index=False
)

In [12]:
from google.colab import files

files.download("gaia_features.csv")